webservers:
  hosts:
    machine1:
      ansible_ssh_port: 2221
      ansible_ssh_private_key_file: "{{ private_key }}"


queue:
  hosts:
    machine2:
      ansible_ssh_port: 2222
      ansible_ssh_private_key_file: "{{ private_key }}"


dbs:
  hosts:
    machine3:
      ansible_ssh_port: 2223
      ansible_ssh_private_key_file: "{{ private_key }}"

datacenter:
  children:
    webservers:
    queue:
    dbs:
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_host: 127.0.0.1
    private_key: "{{ playbook_dir }}/.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"

